### ISSUE TITLE
Generated invalid programming

### ISSUE THREAD

**Issue by coder0505** [allenai/visprog#1]
Hi!
Thanks for sharing your inspiring work. 

When I am running the code, I find that the program generator sometimes gives invalid programming. For example, for the question 'What device is not black?', image ID n282436, in GQA dataset, the generated program is: 

BOX0=LOC(image=IMAGE,object='black')
IMAGE0=CROP_NOT(image=IMAGE,box=BOX0)
ANSWER0=VQA(image=IMAGE0,question='What device is this?')
FINAL_RESULT=RESULT(var=ANSWER0)

However, there is no module named 'CROP_NOT' and it leads to running error. How did you fix such cases in the experiments?

**Comment by BigRedT** [comment]
Yes, that happens sometimes. There are a few ways to deal with such cases:
- Use try-except block while executing to catch such errors and either count this as a failure (like we do during evaluation). In a practical use-case scenario, you could fall back to the VQA model.
- You could try engineering the prompt for program generation by adding a list of functions available and / or adding function docstrings so that GPT3 has more information about what functions it could use and how. 
- You could try generating multiple programs and then reject the invalid ones (e.g. those that invoke invalid modules)
